AllCops:
  Exclude:
    - vendor/bundle/**/*
    - gemfiles/vendor/bundle/**/*
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FileName:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
