AllCops:
  Exclude:
    - vendor/bundle/**/*
    - gemfiles/vendor/bundle/**/*
Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
Metrics/LineLength:
  Exclude:
    - spec/**/*_spec.rb
Style/Documentation:
  Enabled: false
Style/FileName:
  Enabled: false
