language: ruby
sudo: false
cache: bundler
rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1
gemfile:
  - gemfiles/cap3.gemfile
  - gemfiles/cap2.gemfile
before_install:
  - gem update --system --no-document
  - gem i bundler
script:
  - bundle exec rubocop
  - bundle exec rake spec
